// micropolis_web_front/components/game/MapRenderer.tsx
import React, { FunctionComponent } from "react";

import Tile from "./Tile";
import { GameMap } from "@/game/map";

export interface MapRendererProps {
  map: GameMap;
  /** Between 0 and 1. */
  scale?: number;
}

/**
 * TileMap renderer.
 */
const MapRenderer: FunctionComponent<MapRendererProps> = ({ map: { tiles }, scale }) => {
  return (
    <div className="flex">
      {tiles.map((col, colIndex) => (
        <div className="flex-col" key={colIndex}>
          {col.map(({ tileType }, rowIndex) => (
            <Tile
              key={rowIndex}
              row={rowIndex}
              column={colIndex}
              tileIndex={tileType > 0 ? tileType : 0} // dirt for invalid
              atlasImageUrl={"/game/tiles.png"}
              scale={scale ?? 1}
            />
          ))}
        </div>
      ))}
    </div>
  );
};

export default MapRenderer;

// micropolis_web_front/src/lib/game/MapRenderer.svelte
<script lang="ts">
  import Tile from "./Tile.svelte";
  import type { GameMap } from "../../game/map";

  export let map: GameMap;
  /** Between 0 and 1. */
  export let scale: number | undefined = undefined;
</script>

<div class="flex">
  {#each map.tiles as column}
    <div class="flex-col">
      {#each column as tile}
        <Tile scale={scale ?? 1} tileIndex={tile.tileType >= 0 ? tile.tileType : 0} atlasImageUrl="/games/tiles.png" />
      {/each}
    </div>
  {/each}
</div>
