// micropolis_web_front/src/lib/ui/Card.svelte
<script lang="ts">
  import Button from "./Button.svelte";

  export let title: string;
  export let closable: boolean = false;
  export let extraClass: string | undefined = undefined;
  export let onClose: () => void | undefined = undefined;

  $: innerOnClose = onClose ? onClose : () => {};
  const baseClass = "flex flex-col items-center rounded";
  $: innerClass = extraClass ? `${baseClass} ${extraClass}` : baseClass;
</script>

<div class={innerClass}>
  <div class="flex items-center justify-between w-full px-6 py-3 rounded-t">
    <h3 class="font-bold text-gray-400">{title}</h3>
    {#if closable}
      <Button onClick={innerOnClose}>
        <span class="text-sm">X</span>
      </Button>
    {/if}
    <slot />
  </div>
</div>

// micropolis_web_front/components/common/Card.tsx
import React, { FunctionComponent } from "react";

import Button from "./Button";

export interface CardProps {
  title: string;
  closable?: boolean;
  onClose?: () => void;
}

const Card: FunctionComponent<CardProps> = ({
  children,
  title,
  closable = false,
  onClose = () => {},
}) => (
  <div className="flex flex-col items-center rounded">
    <div className="w-full flex items-center justify-between py-3 px-6 rounded-t">
      <h3 className="font-bold text-gray-400">{title}</h3>
      {closable &&
        <Button onToggle={onClose}>
          <span className="text-sm">X</span>
        </Button>
      }
    </div>
    {children}
  </div>
);

export default Card;
