// micropolis_web_front/src/lib/Nav.svelte
<nav>
  <h1 class="text-2xl">
    <a sveltekit:prefetch href="/">micropolis-rs</a>
  </h1>
  <ul class="flex items-center">
    <li class="mr-8">
      <a sveltekit:prefetch href="/about">About</a>
    </li>
    <li>
      <a href="https://github.com/pierreyoda/micropolis-rs" rel="noopener noreferrer" target="_blank">GitHub</a>
    </li>
  </ul>
</nav>

<style lang="postcss">
  nav {
    @apply flex items-center justify-between w-full px-2 py-4;
    @apply font-bold text-white bg-green-900;
  }
</style>

// micropolis_web_front/components/Nav.tsx
import React from "react";
import Link from "next/link";

const Nav = () => (
  <nav className="flex items-center justify-between w-full px-2 py-4 font-bold text-white bg-green-900">
    <h1 className="text-2xl">
      <Link href="/">
        <a>micropolis-rs</a>
      </Link>
    </h1>
    <ul className="flex items-center">
      <li className="mr-8">
        <Link href="/about">
          <a>About</a>
        </Link>
      </li>
      <li className="mr-0">
        <Link href="https://github.com/pierreyoda/micropolis-rs">
          <a>GitHub</a>
        </Link>
      </li>
    </ul>
  </nav>
);

export default Nav;
